"""Deterministic ARCHITECTURE.md from ontology.json (+ hotspots.json if present).

The living-architecture-doc answer to map/code drift: regenerate on every
build/commit and the doc can never lie about structure. No LLM, no API key -
confidence tags carry the honesty."""
from __future__ import annotations

from collections import defaultdict


def _fmt_stats(stats: dict) -> str:
    keep = [(k, v) for k, v in stats.items() if isinstance(v, int) and v]
    return ", ".join(f"{v:,} {k}" for k, v in keep)


def generate_report(onto: dict, hotspots: dict | None = None) -> str:
    L: list[str] = [f"# {onto['name']} - architecture"]
    if onto.get("description"):
        L += ["", onto["description"]]
    L += ["", f"*{_fmt_stats(onto['stats'])}*", ""]
    meta = onto.get("meta", {})
    if meta.get("built_at"):
        L += [f"*Generated by [lensme](https://github.com/yoon-py/lensme) from "
              f"`{meta.get('source_graph', 'graph.json')}` at {meta['built_at']} - "
              f"regenerate with `lensme report`.*", ""]

    # --- structure tree ---
    L += ["## Structure", ""]
    for feat in onto.get("children", []):
        band = " *(supporting)*" if feat.get("kind") == "support" else ""
        L += [f"- **{feat['name']}**{band} - {_fmt_stats(feat.get('stats', {}))}"]
        for comp in feat.get("children", []):
            desc = comp.get("description") or comp.get("rationale") or ""
            conf = comp.get("confidence", "")
            L += [f"  - {comp['name']} ({conf}) - {desc}"]
    L += [""]

    # --- component relationships (rolled up, strongest first) ---
    names = {}

    def walk(n: dict) -> None:
        names[n["id"]] = n["name"]
        for c in n.get("children", []):
            walk(c)

    walk(onto)
    rels = [r for r in onto.get("component_relationships", [])
            if r["relation"] != "integrates_with"]
    if rels:
        L += ["## Component relationships", "",
              "| from | relation | to | refs |", "|---|---|---|---|"]
        for r in sorted(rels, key=lambda r: -r.get("count", 1))[:20]:
            L += [f"| {names.get(r['source'], r['source'])} | {r['relation']} | "
                  f"{names.get(r['target'], r['target'])} | {r.get('count', 1)} |"]
        L += [""]

    # --- externals ---
    if onto.get("external"):
        L += ["## External dependencies", ""]
        used_by: dict[str, list[str]] = defaultdict(list)
        for r in onto.get("component_relationships", []):
            if r["relation"] == "integrates_with":
                used_by[r["target"]].append(names.get(r["source"], r["source"]))
        for e in onto["external"]:
            users = sorted(set(used_by.get(e["id"], [])))
            suffix = f" - used by {', '.join(users)}" if users else ""
            L += [f"- **{e['name']}**{suffix}"]
        L += [""]

    # --- blast radius ---
    impact = onto.get("impact", {})
    ranked = sorted(impact.items(), key=lambda kv: -kv[1]["total_files"])[:5]
    if ranked:
        L += ["## Change impact (blast radius)", "",
              "| component | directly affects | files in radius |", "|---|---|---|"]
        for cid, imp in ranked:
            direct = ", ".join(names.get(i, i) for i in imp["direct"]) or "-"
            L += [f"| {names.get(cid, cid)} | {direct} | {imp['total_files']:,} |"]
        L += [""]

    # --- hotspots (optional; files is a path->commit-count map) ---
    if hotspots and hotspots.get("files"):
        L += [f"## Git hotspots (since {hotspots.get('since', '?')}, "
              f"{hotspots.get('commits_scanned', 0)} commits)", "",
              "| file | commits |", "|---|---|"]
        for path, n in sorted(hotspots["files"].items(), key=lambda kv: -kv[1])[:10]:
            L += [f"| {path} | {n} |"]
        hidden = [p for p in hotspots.get("co_change", []) if not p.get("structural")]
        if hidden:
            L += ["", "**Hidden coupling** (co-change with no structural edge):", ""]
            for p in hidden[:5]:
                L += [f"- `{p['a']}` <-> `{p['b']}` ({p['count']}x together)"]
        L += [""]

    return "\n".join(L)
